# Generated by Django 2.1.8 on 2019-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20190729_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goods_image',
            field=models.ImageField(default='/static/buyer/images/goods/adv01.jpg', upload_to='', verbose_name='商品的图片'),
            preserve_default=False,
        ),
    ]
