# Generated by Django 2.1.8 on 2019-08-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_cart_goods_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品的名称')),
                ('goods_price', models.FloatField(verbose_name='商品的价格')),
                ('goods_image', models.ImageField(upload_to='buyer/images', verbose_name='商品的图片')),
                ('goods_id', models.IntegerField(verbose_name='商品的id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('goods_live', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
