# Generated by Django 2.1.8 on 2019-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_goods_goods_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_aid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='样式id'),
        ),
    ]
