# Generated by Django 2.1.8 on 2019-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_goods_goods_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_aid',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='aid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='样式id'),
        ),
    ]
